const std = @import("std");

pub fn build(b: *std.Build) !void {
    const install_step = b.getInstallStep(); // install the website files to the prefix
    const test_step = b.step("test", "Run tests");
    const check_links_step = b.step("check_links", "Check all links in generated HTML");

    const target = b.resolveTargetQuery(.{}); // native
    const optimize = .ReleaseSafe;

    const pandoc_exe = pandoc_exe: {
        const host = b.graph.host.result;
        // We return here if the dependency hasn't been fetched. The build system will attempt to
        // fetch it and run this (the configure stage) again.
        const dependency = if (host.os.tag == .linux and host.cpu.arch == .x86_64)
            b.lazyDependency("pandoc_linux_amd64", .{}) orelse return
        else if (host.os.tag == .macos and host.cpu.arch == .aarch64)
            b.lazyDependency("pandoc_macos_arm64", .{}) orelse return
        else
            return error.PandocDependencyNotFoundForHost;
        break :pandoc_exe dependency.path("bin/pandoc");
    };

    const vnu_exe = vnu_exe: {
        const host = b.graph.host.result;
        const dependency = if (host.os.tag == .linux and host.cpu.arch == .x86_64)
            b.lazyDependency("vnu_linux_amd64", .{}) orelse return
        else if (host.os.tag == .macos and host.cpu.arch == .aarch64)
            b.lazyDependency("vnu_macos_arm64", .{}) orelse return
        else
            return error.VnuDependencyNotFoundForHost;
        break :vnu_exe dependency.path("bin/vnu");
    };

    install_step.dependOn(step: {
        const website = b.addWriteFiles(); // output folder for website content
        _ = website.addCopyFile(b.path("styles.css"), "styles.css"); // copy in the style file
        _ = website.addCopyFile(b.path("CNAME"), "CNAME"); // custom domain for GitHub Pages

        // This executable collates the list of blog posts, adds it (with links to the pages) to
        // "index.html", and generates the Atom feed. Its arguments are the Zig cache paths to:
        // - all of the blog post HTML files generated by Pandoc,
        // - the input "index.html" generated by Pandoc,
        // - the output "index.html" (where the final index will be written),
        // - and the output "atom.xml".
        const build_index_run = b.addRunArtifact(
            b.addExecutable(.{
                .name = "blog_list_builder",
                .root_module = b.createModule(.{
                    .root_source_file = b.path("src/blog_list_builder.zig"),
                    .target = target,
                    .optimize = optimize,
                }),
            }),
        );
        const updated_index =
            build_index_run.addPrefixedOutputFileArg("--index-out=", "index.html");
        const atom_feed = build_index_run.addPrefixedOutputFileArg("--feed=", "atom.xml");

        _ = website.addCopyFile(updated_index, "index.html"); // copy in the final "index.html"
        _ = website.addCopyFile(atom_feed, "atom.xml"); // copy in the generated feed

        // Process website content. Non-Markdown files are copied directly to the output. HTML is
        // generated from Markdown files using Pandoc.
        var dir = try std.fs.cwd().openDir("content", .{ .iterate = true });
        defer dir.close();
        var walker = try dir.walk(b.allocator);
        defer walker.deinit();
        while (try walker.next()) |entry| {
            if (entry.kind != .file) continue;

            const filepath = b.path(b.pathJoin(&.{ "content", entry.path }));
            const filename = entry.basename;

            // Copy in non-Markdown files (assets).
            if (!std.mem.endsWith(u8, entry.basename, ".md")) {
                _ = website.addCopyFile(filepath, entry.path); // preserve file structure
                continue;
            }

            // Blog posts start with the publication date and have the format "YYYYMMDD-*.md": eight
            // digits followed by a "-".
            const is_blog_post = filename.len >= 9 and filename[8] == '-' and has_yyyymmdd: {
                for (filename[0..8]) |c| if (!std.ascii.isDigit(c)) break :has_yyyymmdd false;
                break :has_yyyymmdd true;
            };

            // Create a Pandoc step for each Markdown file to generate HTML from the Markdown.
            const pandoc_step = std.Build.Step.Run.create(b, b.fmt("pandoc: {s}", .{filename}));
            pandoc_step.addFileArg(pandoc_exe);
            pandoc_step.addArgs(&.{
                "--from=markdown",
                "--to=html5",
                "--fail-if-warnings=true",
                "--shift-heading-level-by=1", // # -> ##
            });
            pandoc_step.addPrefixedFileArg("--template=", b.path("template.html"));
            pandoc_step.addPrefixedFileArg("--css=", b.path("styles.css"));
            pandoc_step.addPrefixedFileArg("--lua-filter=", b.path("pandoc/title-from-h1.lua"));
            pandoc_step.addPrefixedFileArg("--lua-filter=", b.path("pandoc/fix-md-links.lua"));
            if (is_blog_post) { // pass the publication date as metadata to Pandoc
                const year = filename[0..4]; // YYYY
                const month = filename[4..6]; // MM
                const day = filename[6..8]; // DD
                pandoc_step.addArg(b.fmt("--metadata=date:{s}-{s}-{s}", .{ year, month, day }));
            }
            pandoc_step.addFileArg(filepath);
            const generated_html_path = pandoc_step.captureStdOut();

            // Map "*.md" -> "*.html" (e.g. "index.md" -> "index.html").
            const html_filename = b.fmt("{s}.html", .{filename[0 .. filename.len - ".md".len]});

            if (std.mem.eql(u8, filename, "index.md")) {
                // Don't copy in "index.html". This step will save the final "index.html".
                build_index_run.addPrefixedFileArg("--index-in=", generated_html_path);
                continue;
            }

            if (is_blog_post) build_index_run.addPrefixedFileArg(
                b.fmt("--blog-post={s}:", .{html_filename}), // need the filename for the hyperlink
                generated_html_path,
            ); // e.g. "--blog-post=20250705-i-like-coffee.html:{zig-cache-path}/stdout"

            _ = website.addCopyFile(generated_html_path, html_filename); // copy in generated HTML
        }

        break :step &b.addInstallDirectory(.{
            .source_dir = website.getDirectory(),
            .install_dir = .prefix,
            .install_subdir = ".",
        }).step;
    });

    const html_dir = b.getInstallPath(.prefix, "");

    test_step.dependOn(step: {
        const validate_html = std.Build.Step.Run.create(b, "vnu: validate HTML");
        validate_html.addFileArg(vnu_exe);
        validate_html.addArgs(&.{
            "--Werror",
            "--filterpattern",
            ".*Trailing slash.*",
            "--skip-non-html",
            html_dir,
        });
        validate_html.step.dependOn(install_step);
        break :step &validate_html.step;
    });

    test_step.dependOn(step: {
        const validate_css = std.Build.Step.Run.create(b, "vnu: validate CSS");
        validate_css.addFileArg(vnu_exe);
        validate_css.addArgs(&.{ "--Werror", "--skip-non-css", html_dir });
        validate_css.step.dependOn(install_step);
        break :step &validate_css.step;
    });

    check_links_step.dependOn(step: {
        const check_links_exe = b.addExecutable(.{
            .name = "check_links",
            .root_module = b.createModule(.{
                .root_source_file = b.path("src/check_links.zig"),
                .target = target,
                .optimize = optimize,
            }),
        });
        const check_links_options = b.addOptions();
        check_links_options.addOption([]const u8, "html_dir", html_dir);
        check_links_exe.root_module.addOptions("config", check_links_options);
        const run_check_links = b.addRunArtifact(check_links_exe);
        run_check_links.step.dependOn(install_step);
        break :step &run_check_links.step;
    });
}
