name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          # FIXME: Remove this once 0.17.0 is out. See
          # https://codeberg.org/ziglang/zig/issues/31964.
          version: "0.17.0-dev.1099+7db2ef610"
      - name: "Build website and run tests" # installed to ./zig-out
        run: zig build test
      - uses: actions/upload-pages-artifact@v3
        with:
          path: zig-out
      - uses: actions/deploy-pages@v4
